### ISSUE TITLE
Dev. mode no cursor

### ISSUE THREAD

**Issue by VladCorvi** [onnoj/DeusExEchelonRenderer#1]
Firstly. Thank you for amazing work! 
 
My issue: While in developer mode - **alt + X**, mouse dont appear. **alt + Del** doesent help. So cant adjust DLSS quality. 
![DeusEx_zUTtoFIGfm](https://github.com/onnoj/DeusExEchelonRenderer/assets/25734703/6b344eb3-569e-4e48-8201-9d97ce18ef2a)
How to unlock mouse in dev mode?

Also asking for Remix support for Deus Ex: Revision. (black screen with sky now).

**Comment by onnoj** [comment]
Hi @VladCorvi,

If you're using Deus Exe, it by default hijacks your cursor. You can turn this behavior off in its settings:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/a9ada2ca-8334-48ac-a7dd-d3185e336057)
Could you let me know if that fixes it?

As for Deus Ex Revision, you'll have to ask their mod team, support is beyond the scope of this project, but, if they have any fixes I'll be happy to merge them in.

**Comment by onnoj** [comment]
Issue solved by disabling 'Raw Input'
