### ISSUE TITLE
🕷️[BUG/CRASH/GLITCH] ... I followed the setup guidelines sted by step but it doesn't work

### ISSUE THREAD

**Issue by Iraito** [onnoj/DeusExEchelonRenderer#18]
I followed the guide, do i need to install omniverse or something else?

* [remix-0.5.1]
* [v0.2.6]
* Fresh installation of DE from steam
* GPU: 4080

**Comment by onnoj** [comment]
Hi, 

Can you be a bit more specific? What doesn't work? How far do you get? Were you able to follow the instructions to the letter or were there steps that were unclear?

And, to answer your question, you don't need to install Omniverse, that's meant for modding.

**Comment by Iraito** [comment]
I follow the guide, start the game but i don't get any RTX, no message or anything.
Also i'm interested in this primarily for modding, i have been working as a 3d artist for a long time now and i wanted a small side project to work on, if i need omniverse for that i will add that too, but as of now i first wanna get the game to have RTX on.

**Comment by onnoj** [comment]
Can you add a screenshot of what it looks like?

**Comment by Iraito** [comment]
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/3323267/34985634-da6e-4461-9bf5-5f8240293538)

**Comment by onnoj** [comment]
Alright, for some reason the game is using the default renderer. 

Can you make a screenshot of the Deus Exe configuration menu? It should look like this: 
![324254889-0a78b852-3060-4ff9-8dbc-320f0d078dd0](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/aabc54a2-7833-451d-b18a-47a5e6d936ed)

**Comment by Iraito** [comment]
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/3323267/45b99ac7-dda5-46e8-ae1e-be9c9dca8c5e)

**Comment by Iraito** [comment]
Any news?

**Comment by onnoj** [comment]
Hi, I'm currently away for business. I should have time to look into the issue this weekend. 

In the mean time, could you see if you can locate the logs? [How to](/onnoj/DeusExEchelonRenderer/wiki/How-to-collect-debugging-information)

There should also be a way to force Deus Exe to not use the user data folders, but I don't remember what the command line flag was.
Edit: found it, it's -localdata (https://kentie.net/article/dxguide/files/Readme.htm)

**Comment by Iraito** [comment]
Did the local data still not working, i will wait for a fix.

**Comment by onnoj** [comment]
Can you provide logs?

**Comment by Iraito** [comment]
[deusex.log](https://github.com/onnoj/DeusExEchelonRenderer/files/15395963/deusex.log)

**Comment by mmdanggg2** [comment]
It says it can't load the package but, assuming you've put the dll into the System folder correctly, here's a bit of a random guess.
Go into the properties of the dll and see if you need to unblock it:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/3161587/04ca0fdf-d0ad-4cee-b595-e805be95b273)
Just check unblock and apply, then try again.

**Comment by Iraito** [comment]
Everything was already unblocked

**Comment by anchorlightforge** [comment]
This is a bit of a shot in the dark, but someone that was testing Red Faction II with me a while back had an Nvidia driver setting that overrode the default behavior and caused Remix not to load at all.

In the Nvidia Control Panel, `Vulkan/OpenGL Present Method` was set to this:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/55258193/d7c47160-c908-4c4e-9435-bbc85512a4da)

When it should be set to this:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/55258193/b16e00fe-16fc-4dce-ad23-91896a8e0ebb)

It's the last setting on the Nvidia Control Panel in Manage 3D Settings > Global Settings.

To be clear, I'm posting this assuming from the post above that:
- Remix is not rendering (as demonstrated, display is rasterized)
- Remix is not hooking at all (Alt-X Remix menu and welcome message is not appearing)
- Echelon Renderer appears, and is installed correctly

If this doesn't do the trick, I'll try to find some time to investigate.

**Comment by Iraito** [comment]
Nope, still not working but thank you all.

**Comment by onnoj** [comment]
Hmm, well, the issue is that the .DLL isn't being loaded, maybe something is blocking it (some overzealous antivirus software?), or the runtime library is not properly installed. 

If it's the latter, you could try installing it to see if it makes a difference, it's [vc_redist.x86.exe](https://aka.ms/vs/17/release/vc_redist.x86.exe) on this page: 
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

If that doesn't work, then I'm afraid I'm out of ideas until someone else runs into the same problem.

**Comment by onnoj** [comment]
Issue cannot be reproduced. No response in 2w, closing issue. Feel free to reopen!

**Comment by Iraito** [comment]
Yeah tried everything, still not working.
