### ISSUE TITLE
🕷️[BUG] No lights

### ISSUE THREAD

**Issue by Nevrose** [onnoj/DeusExEchelonRenderer#21]
**Describe the bug**
* A clear and concise description of what the bug is : the whole world is black. No lights are rendered (you only can see the computer screens, the UI and the light "bulbs").
* What version of RTX Remix you're using : remix-0.5.4-release.zip
* What version of the renderer you are using : DeusExEchelonRenderer-v0.3.7.zip
* Which version of Deus Ex you have; is it from Steam or GOG, was it modded or freshly installed? : DeusExe-v8.1.zip (replacing steam GOTY)
* Whether other RTX Remix games work (such as [Portal with RTX](https://store.steampowered.com/app/2012840/Portal_with_RTX/)) : none I am aware of, but Portal RTX crashes at launch.
* GPU : RTX 4090
* CPU : AMD Ryzen Threadripper 2920X
* OS : Windows 10
* Nvidia Pilot : 560.81

**What to attach**
![without_flashlight](https://github.com/user-attachments/assets/1c57f8fe-cc7b-4efb-97ce-856460ab8f7f)
![with_flashlight](https://github.com/user-attachments/assets/8fe02771-e337-44c5-b691-69a5039eef35)
![deus_exe_configuration](https://github.com/user-attachments/assets/230c67be-1e75-411b-bc8c-a90817670b1e)
![menu](https://github.com/user-attachments/assets/55ef1adf-153e-4ca8-b391-e9e24866e054)

**To Reproduce**
Just load a game.

**Expected behavior**
Rendered lights.

**Additional context**
I already did "Verify integrety of game files" and then re-unzipped all three zips in the system folder. (remix-0.5.4-release.zip, DeusExEchelonRenderer-v0.3.7.zip, DeusExe-v8.1.zip).

**Comment by onnoj** [comment]
Hi! 

Sorry for the late response!
Can you attach the various log files described here?

https://github.com/onnoj/DeusExEchelonRenderer/wiki/How-to-collect-debugging-information#collecting-the-log-files

Also, did you have at any point any mods installed?

In the mean time, could you temporarily copy and rename DeusEx.exe to DeusExTest.exe and start the executable directly from System? See if that changes anything?

Finally, this sounds like it might be a more generic bug with RTX Remix and/or your driver's, but I'll know more with the log files.

**Comment by onnoj** [comment]
No user response, feel free to reopen!
