### ISSUE TITLE
[Feature] Implement texture filtering (and honor PF_NoSmooth)

### ISSUE THREAD

**Issue by DaSk79130569** [onnoj/DeusExEchelonRenderer#4]
Amazing work on this mod. Just really really great effort for this amazing game!

It seems texture filtering is turned off for me, the textures look pixelated composed of big pixel chunks.
If this is an artistic retro choice, how do I re-enable texture filtering.

**Comment by onnoj** [comment]
Can you include a screenshot?

**Comment by DaSk79130569** [comment]
![Untitled](https://github.com/onnoj/DeusExEchelonRenderer/assets/81931582/248b4462-655b-4e19-8bc7-86cfe5a4757e)

Yes, screenshot attached.

**Comment by onnoj** [comment]
I'll have to check when I'm back from vacation how much of that is normal versus maybe a bug. 

RTX Remix and this renderer add raytracing to the game, but doesn't remaster the game in any other way, the textures are the original ones the game shipped with. 

In due time, there will hopefully be graphics mods that use this renderer and RTX Remix to do a graphical overhaul, but until then you're stuck with the original textures, just with real-time lighting

**Comment by DaSk79130569** [comment]
![Untitled2](https://github.com/onnoj/DeusExEchelonRenderer/assets/81931582/4344b809-1d59-4cac-87ce-60ff19207ed0)

Here is a screenshot of the same place with a conventional D3D renderer. I understand the textures are the same. But the RTX renderer is definitely doing something to texture filtering. 

Thanks for the great work!

**Comment by onnoj** [comment]
Back home now, and checked the code base. Currently the texture sampler is not configured, so the D3D9/Remix default to D3DTEXF_POINT.
This needs to be fixed in the renderer, where it needs to take into account that point filtering is used instead when PF_NoSmooth is set. Not sure if linear filtering should be used or anisotropic filtering with the max supported value.

**Comment by DaSk79130569** [comment]
No expert on this but I feel like GPUs capable to run this would likely be OK with 16xAF. Or making trilinear filtering default and letting user to set 16xAF via nVIdia control panel override.

**Comment by onnoj** [comment]
Fixed by RCGodward and released as per version https://github.com/onnoj/DeusExEchelonRenderer/releases/tag/v0.1.18
Thanks @DaSk79130569 for noticing the issue and reporting it, and thank you @RCGodward for fixing it.
