### ISSUE TITLE
Lamp asset glitch

### ISSUE THREAD

**Issue by shelterx** [onnoj/DeusExEchelonRenderer#9]
Pressing F12 to enable "flashlight" and toggling the lamp on the desk in the training mission makes the lamp on the desk disappear, quite possible it might happen to other assets as well.
OpenGL renderer:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/8688458/488c8622-f1cf-4c3d-9e53-930f27e51b12)
Echelon Renderer
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/8688458/b144fead-fd15-4ced-ba9d-5b23f8aba032)

The lamp on the desk also does not emit any light source when toggled on when using echelon.

**Comment by onnoj** [comment]
hah, that's amazing, I'll investigate :D
Default rtx.conf?

**Comment by shelterx** [comment]
I haven't changed anything really

**Comment by shelterx** [comment]
It seems like just turning on the lamp makes it disappear, it's more visible in v0.1.18 (pressing F12 just makes it even more visible).
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/8688458/b46c566c-adf4-4637-bbe1-06fdf5c2d31a)

**Comment by UnklePhunkle** [comment]
must be the same transparency effect used when picking an object up. I don't know the inner workings of the game, but it seems like the lamp is has the wrong flags for what should happen when interacted with.

**Comment by onnoj** [comment]
I don't have a lot of time to investigate, but, the difference in the renderer between the light turned on and off is the following blend state:
| On | Off |
|--------|--------|
| Alpha Blend Enable: **True** | Alpha Blend Enable: **False**
| Blend Operation: D3DBLENDOP_ADD | Blend Operation: D3DBLENDOP_ADD
| Blend Source: D3DBLEND_ONE | Blend Source: D3DBLEND_ONE
| Blend Destination: **D3DBLEND_INVSRCCOLOR** | Blend Destination: **D3DBLEND_ZERO**
| Blend Factor: D3DCOLOR_ARGB(0xff,0xff,0xff,0xff) | Blend Factor: D3DCOLOR_ARGB(0xff,0xff,0xff,0xff)
| Separate Alpha Blend Enable: False | Separate Alpha Blend Enable: False
| Alpha Blend Operation: D3DBLENDOP_ADD | Alpha Blend Operation: D3DBLENDOP_ADD
| Alpha Blend Source: D3DBLEND_ONE | Alpha Blend Source: D3DBLEND_ONE
| Alpha Blend Destination: D3DBLEND_ZERO | Alpha Blend Destination: D3DBLEND_ZERO |
 
I'll see what I can find later. Might be that the texture is having the PF_Translucent flag added.
Wondering if it should be unlit instead.

**Comment by onnoj** [comment]
Should be fixed now!
https://github.com/onnoj/DeusExEchelonRenderer/releases/tag/v0.2.2
